build:
	go mod tidy
	go build -o bin/go-aws-ec2 cmd/go-aws-ec2/main.go
	go build -o bin/go-hetzner-vps cmd/go-hetzner-vps/main.go
	go build -o bin/go-digital-ocean-droplet cmd/go-digital-ocean-droplet/main.go
