#! /bin/bash

# Show the data for a given address based on miners.json generated by unusual-block-delay.py

validator_addr=$1
echo "Raw Data for ${validator_addr}:"
# Check if the jq command returns null
if [ "$(jq -e '.["'${validator_addr}'"]' miners.json)" == "null" ]; then
    echo "No data found for ${validator_addr}. Exiting."
    exit 1
else
    jq '.["'${validator_addr}'"]' miners.json
fi
# Number of blocks above 2s for a given address
echo -n "Number of long blocks time: "
num_elements=$(jq '.["'${validator_addr}'"] | length' miners.json)
echo $num_elements blocks

# Total time above 2s for a given address
echo -n "Total block time duration: "
total_time=$(jq '.["'${validator_addr}'"] | map(.[] | values) | add' miners.json)
echo $total_time seconds

# Total time losses by the network
echo -n "Total time losses by the network: "
total_time_losses=$(echo "$total_time - ($num_elements * 2)" | bc)
echo $total_time_losses seconds